spring:
  profiles:
    active: local
    include:
      - domain
      - external
      - oauth

  ## OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 544385537574-774c31vj941hkdl0fp70vt0skjc3je3n.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1129306567796641
            client-secret: 906862fcf400aec6f0e4b28452eb0be6
            scope:
              - email
              - public_profile
          kakao:
            client-id: c72139d8987d18a01da876852d181267
            redirect-uri: https://i7b306.p.ssafy.io/login/oauth2/code/kakao #기본 제공 클라이언트가 아니기 때문에 반드시 적어줘야 함. 그래서 아무거나 적어도 되지만 되도록 규칙에 맞추기
            client-authentication-method: POST
            authorization-grant-type: authorization_code #oauth2의 코드 방식 사용
            scope: profile_nickname, account_email
            client-name: Kakao
          naver:
            client-id: KJPFs_Lf5t3L81JjcKWR
            client-secret: mbaBXEF8TR
            redirect-uri: https://i7b306.p.ssafy.io/login/oauth2/code/naver # /login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response # attributes를 json으로 받을 때 네이버는 reponse라는 키 값으로 리턴

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  ## SMTP 설정
  mail:
    host: smtp.gmail.com
    port: 465
    username: wolfmob9612@gmail.com
    password: ingjpyytdhsojlxg
    protocol: smtps
    properties: # 전송 위한 prop, ssl의 신뢰 및 권한 등 사용허가
      mail.smtp.auth: true
      mail.smtp.enable: true
      mail.smtp.timeout: 5000
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.socketFactory:fallback: true

token:
  expiration_time: 7200000 # 2시간 (7200000)
  refresh_token_expiration_time: 604800000 # 7일
  secret: secret


